### ISSUE TITLE
求一个一键安装的方式，GO语言的搞不明白，内网环境也不好拖git的回来

### ISSUE THREAD

**Issue by bozarzza** [myleo1/JDC-Monitor#1]

**Comment by Huang28** [comment]
去群晖环境  已经装了influxdb和grafana 但是教程说influxdb表名很重要然后就没然后了。
我猜修改project.dir为项目目录应该是搭建golang环境运行后。下载作者code复制进去。然后填写influxdb信息运行应该就是那个表名。
新手的我还找不到群晖怎么搭建golang环境，只能等作者做成docker我pull或者我问群友了。

**Comment by myleo1** [comment]
> 去群晖环境 已经装了influxdb和grafana 但是教程说influxdb表名很重要然后就没然后了。
> 我猜修改project.dir为项目目录应该是搭建golang环境运行后。下载作者code复制进去。然后填写influxdb信息运行应该就是那个表名。
> 新手的我还找不到群晖怎么搭建golang环境，只能等作者做成docker我pull或者我问群友了。

需要自己建influxDB的库，记住名字，填入config.json中的dbName,库中的表名是自动生成的，具体的表名是会自动获取京东云的MAC地址然后自动生成的，一个京东云设备对应一个表，然后grafana里需要自己写select语句，获取对应MAC地址的京东云设备的相关信息。
至于指定project.dir主要是为了存储日志文件。还有，golang环境并不需要配置，go是编译型语言，我已release编译好的可执行文件，直接使用即可。

------------------
关于docker或者一键搭建，等之后空闲之后再弄吧，最近比较忙。可能要到七八月份。

**Comment by Huang28** [comment]
> > 去群晖环境已经装了influxdb和grafana但是教程说influxdb表名很重要然后就没然后了。
> > 我猜修改project.dir为项目目录应该是golang环境运行后。下载作者代码复制进去。然后填写influxdb信息运行应该就是那个表名
> > 。
> 
> 需要自己建influxDB的库，记住名字，填入config.json中的dbName，库中的表名是自动生成的，具体的表名是会自动获取京东云的MAC地址然后自动生成的，一个京东云设备对应一个表，然后grafana里需要自己写选择语句，获取对应的MAC地址的京东云设备的相关信息。
> 至于指定project.dir主要是为了存储日志文件。还有，golang环境并不需要配置，去是编译型语言，我已发布编译好的替代文件，直接使用即可。
> 
> 关于docker或一键构造，等之后之后之后再弄吧，最近比较忙。可能要到七八月份。

 {
  "project": {
    "dir": "/volume3/docker/jdc/"
  },
  "influx": {
    "url": "127.0.0.1:8086",
    "user": "xxx",
    "pwd": "xxx",
    "dbName": "xxx"
  },
  "jd": [
    {
      "user": "xxx",
      "pin": "xxxxx",
      "tgt": "xxxxxxx",
      "getZXQC": true,
      "collect": false
    }
  ],
  "wechat": {
    "api": "http://127.0.0.1:9000/wechat-work-pusher/msg",
    "token": "xxxxxxxx"
  }
}

要装3个docker  分别是influxdb grafana和wechat-work-pusher
运行是cd到jd-mining-server_linux_amd64的文件下 
./jd-mining-server_linux_amd64 执行回车
可能是我群晖环境问题 ，好像没有数据！暂时不折腾，等作者出docker在看看。
感谢作者分享，不急，有空在折腾。

**Comment by myleo1** [comment]
> > > 去群晖环境已经装了influxdb和grafana但是教程说influxdb表名很重要然后就没然后了。
> > > 我猜修改project.dir为项目目录应该是golang环境运行后。下载作者代码复制进去。然后填写influxdb信息运行应该就是那个表名
> > > 。
> > 
> > 
> > 需要自己建influxDB的库，记住名字，填入config.json中的dbName，库中的表名是自动生成的，具体的表名是会自动获取京东云的MAC地址然后自动生成的，一个京东云设备对应一个表，然后grafana里需要自己写选择语句，获取对应的MAC地址的京东云设备的相关信息。
> > 至于指定project.dir主要是为了存储日志文件。还有，golang环境并不需要配置，去是编译型语言，我已发布编译好的替代文件，直接使用即可。
> > 关于docker或一键构造，等之后之后之后再弄吧，最近比较忙。可能要到七八月份。
> 
> {
> "project": {
> "dir": "/volume3/docker/jdc/"
> },
> "influx": {
> "url": "127.0.0.1:8086",
> "user": "xxx",
> "pwd": "xxx",
> "dbName": "xxx"
> },
> "jd": [
> {
> "user": "xxx",
> "pin": "xxxxx",
> "tgt": "xxxxxxx",
> "getZXQC": true,
> "collect": false
> }
> ],
> "wechat": {
> "api": "http://127.0.0.1:9000/wechat-work-pusher/msg",
> "token": "xxxxxxxx"
> }
> }
> 
> 要装3个docker 分别是influxdb grafana和wechat-work-pusher
> 运行是cd到jd-mining-server_linux_amd64的文件下
> ./jd-mining-server_linux_amd64 执行回车
> 可能是我群晖环境问题 ，好像没有数据！暂时不折腾，等作者出docker在看看。
> 感谢作者分享，不急，有空在折腾。

你提供日志看一下，config.json有没有放到和可执行文件同一个目录下？

**Comment by Huang28** [comment]
> > > > 去群晖环境已经装了influxdb和grafana但是教程说influxdb表名很重要然后流入了。
> > > > 我想修改dir为项目目录应该是golang环境运行后。下载作者代码复制进去。然后流入db信息运行应该就是那个表名
> > > > 。
> > > 
> > > 
> > > 需要自己建influxDB的库，记住名字，填入config.json中的dbName，库中的表名是自动生成的，具体的表名是自动获取京东云的地址然后自动生成的，一个京东云设备对应表，然后grafana里自己写选择语句，获取对应的MAC地址的京东云设备的相关信息。
> > > 至于指定项目。目录主要是为了存储日志文件。还有，golang环境不需要配置，去是编译型语言，我已经发布了编译好的备选文件，直接用于
> > > 关于码头工人或一键构造，等之后再弄吧，最近比较忙。可能要到七八月份。
> > 
> > 
> > { 
> > "project": { 
> > "dir": "/volume3/docker/jdc/" 
> > }, 
> > " influx ": { 
> > "url": "127.0.0.1:8086", 
> > "user": "xxx", 
> > "pwd": "xxx", 
> > "dbName": "xxx" 
> > }, 
> > "jd": [ 
> > { 
> > "user": "xxx", 
> > "pin": "xxxxx", 
> > "tgt": 
> > "xxxxxxxx" , "getZXQC": true, 
> > " collect": false 
> > } 
> > ], 
> > "wechat": { 
> > "api": " http://127.0.0.1:9000/wechat-work-pusher/msg ", 
> > "token": "xxxxxxxx"
> > } 
> > }
> > 要装3个docker 分别是influxdb grafana和wechat-work-pusher
> > 运行是cd到jd-mining-server_linux_amd64的文件下
> > ./jd-mining-server_linux_amd64 执行回车
> > 可能是我群晖环境问题 ，好像没有数据！暂时不折腾，等作者出docker在看看。
> > 感谢作者分享，不急，有空在折腾。
> 
> 你提供日志看一下，config.json有没有放到和可执行文件同一个目录下？

![image](https://user-images.githubusercontent.com/52352624/120071504-565c2580-c0c2-11eb-83f5-becc62678a24.png)
如果是没有config的话会报错。log会输出
{"level":"FATAL","time":"2021-05-29T21:11:26.426+0800","msg":"read jd config err"}
但是我是有config的 
最大可能是我influxdb和grafana或者wechat没有跟config匹配好
所以才执行不成功卡住了。

**Comment by 84896150** [comment]
不知道是哪里配置有问题
root@frpc1:/home# ./jd-mining-server_linux_amd64 
2021/07/27 13:29:51 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
panic: exception: 获取路由器列表失败
Exception StackTrace: 
jd-mining-server/service/service.go:75
jd-mining-server/service/service.go:17
jd-mining-server/cmd/root.go:31
runtime/asm_amd64.s:1371


goroutine 6 [running]:
jd-mining-server/service.ListRouter(0xc000036550, 0x10, 0xc00007a1e0, 0x60, 0x0, 0x0, 0x0)
        jd-mining-server/service/service.go:75 +0x120e
jd-mining-server/service.InitRouterList(0xc000036550, 0x10, 0xc00007a1e0, 0x60)
        jd-mining-server/service/service.go:17 +0x4d
jd-mining-server/cmd.run(0xc0004df4c0)
        jd-mining-server/cmd/root.go:31 +0x49
created by jd-mining-server/cmd.glob..func1
        jd-mining-server/cmd/root.go:24 +0xa5
root@frpc1:/home#

**Comment by myleo1** [comment]
> 不知道是哪里配置有问题
> root@frpc1:/home# ./jd-mining-server_linux_amd64
> 2021/07/27 13:29:51 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
> panic: exception: 获取路由器列表失败
> Exception StackTrace:
> jd-mining-server/service/service.go:75
> jd-mining-server/service/service.go:17
> jd-mining-server/cmd/root.go:31
> runtime/asm_amd64.s:1371
> 
> goroutine 6 [running]:
> jd-mining-server/service.ListRouter(0xc000036550, 0x10, 0xc00007a1e0, 0x60, 0x0, 0x0, 0x0)
> jd-mining-server/service/service.go:75 +0x120e
> jd-mining-server/service.InitRouterList(0xc000036550, 0x10, 0xc00007a1e0, 0x60)
> jd-mining-server/service/service.go:17 +0x4d
> jd-mining-server/cmd.run(0xc0004df4c0)
> jd-mining-server/cmd/root.go:31 +0x49
> created by jd-mining-server/cmd.glob..func1
> jd-mining-server/cmd/root.go:24 +0xa5
> root@frpc1:/home#

检查一下pin和tgt是否正确

**Comment by Today-to-Lsp** [comment]
> > 去群晖环境 已经装了influxdb和grafana 但是教程说influxdb表名很重要然后就没然后了。
> > 我猜修改project.dir为项目目录应该是搭建golang环境运行后。下载作者code复制进去。然后填写influxdb信息运行应该就是那个表名。
> > 新手的我还找不到群晖怎么搭建golang环境，只能等作者做成docker我pull或者我问群友了。
> 
> 需要自己建influxDB的库，记住名字，填入config.json中的dbName,库中的表名是自动生成的，具体的表名是会自动获取京东云的MAC地址然后自动生成的，一个京东云设备对应一个表，然后grafana里需要自己写select语句，获取对应MAC地址的京东云设备的相关信息。 至于指定project.dir主要是为了存储日志文件。还有，golang环境并不需要配置，go是编译型语言，我已release编译好的可执行文件，直接使用即可。
> 
> 关于docker或者一键搭建，等之后空闲之后再弄吧，最近比较忙。可能要到七八月份。

大佬，7、8月份已经过了，有空写个docker-compose教程了吗
