### ISSUE TITLE
采集到的数据方差太大

### ISSUE THREAD

**Issue by HaloWww** [myleo1/JDC-Monitor#11]
请问采集到的upload数据该如何处理呢？需要除5除1024么？

现在搭建的表格数据方差太大，感觉有些失真了

![image](https://user-images.githubusercontent.com/64211024/164960367-1740bd66-02cd-4882-82b6-9ec0a795aa53.png)

**Comment by myleo1** [comment]
原始数据的单位是kbps，除以1024就等于Mbps，方差太大可以考虑增加一下数据密度点，默认采集是1m一次

**Comment by HaloWww** [comment]
请问可以分享一下General的panel模板链接么？这个的中文教程实在是太少了，想研究一下总流量统计是怎么实现的。感谢

**Comment by myleo1** [comment]
> 请问可以分享一下General的panel模板链接么？这个的中文教程实在是太少了，想研究一下总流量统计是怎么实现的。感谢

提交到项目中了，详细请看更新日志
