### ISSUE TITLE
没有pin参数

### ISSUE THREAD

**Issue by kcufId** [myleo1/JDC-Monitor#12]
老铁们，收集抓包(burp 代理)怎么一直没有pin的参数呀，有tgt的，是不是app给内置了，还是有这参数的不走代理？ 
ios: 14.5
app: v3.4.0

随便命名一个就行了。。

**Comment by myleo1** [comment]
由于京东云无线宝APP更新后http请求时不再需要pin参数了，在早期版本中是需要的，已经在http request中去掉pin参数，但pin作为map的key用于区分不同用户的路由器，故暂时做了保留处理，可以随意填写，多用户时注意不重复即可。 
see: https://github.com/myleo1/JDC-Monitor/commit/630eba723e544cc873258024a15bd5a05e68a0ea
