### ISSUE TITLE
4.0更新了 可以通过一个接口拿到所有路由的状态信息

### ISSUE THREAD

**Issue by wang-st** [myleo1/JDC-Monitor#14]
iOS版本安装链接：https://testflight.apple.com/join/tQyd1h4T
Android版本安装链接：https://www.pgyer.com/6sW2
大佬有空可以看卡
我试了下 报错401

**Comment by myleo1** [comment]
是指本仓库的代码（旧版本接口）出现401了还是新版本接口401了呢？
如果是本仓库代码，请附上401的接口地址，如果是新版本，有空一起研究下。

**Comment by wang-st** [comment]
新版 获取全部路由信息的接口401

**Comment by myleo1** [comment]
> 新版 获取全部路由信息的接口401

1、具体是哪个接口，刚粗略看了一下貌似和旧版没有太大区别，没有找到拿到所有路由的状态信息的接口，我看还是一个个设备进行请求的；
2、接口鉴权方法好像也没有区别；
3、你可以提供接口的url吗？

**Comment by wang-st** [comment]
https://gw.smart.jd.com/s/service/device/searchUserDevice
需要需要点下搜索才能拿到这个接口 
接口鉴权方法 我用你之前的 返回失败 不知道是不是我参数错了

**Comment by myleo1** [comment]
> https://gw.smart.jd.com/s/service/device/searchUserDevice 需要需要点下搜索才能拿到这个接口 接口鉴权方法 我用你之前的 返回失败 不知道是不是我参数错了

1、接口按照原先的鉴权方法是可以通的，需要注意cryptokit.EncodeAuthorization中的deviceKey加密方法，其中iPhone的型号、版本需要和新版本抓包获得的URL中的hard_platform、plat_version等参数对应。

2、但是这个接口返回的数据中，有时有所有路由的状态信息，而有时又没有。
- 怀疑/s/service/device/searchUserDevice接口返回的路由状态信息其实是缓存值，当有请求至/f/service/controlDevice接口时，同时请求/s/service/device/searchUserDevice接口才会有值返回。
- 一段时间不请求/f/service/controlDevice接口，/s/service/device/searchUserDevice返回中没有相应信息。
- /f/service/controlDevice接口其实会下发查询的命令，比如获取当前状态或是获取路由列表，当有命令下发时，请求/s/service/device/searchUserDevice接口才有返回。
