### ISSUE TITLE
docker 运行报错 read jd config err这是因为什么

### ISSUE THREAD

**Issue by QinChBeSt** [myleo1/JDC-Monitor#18]
FATAL   read jd config err
 miss config.json: Config File "config" Not Found in "[/root]"

**Comment by myleo1** [comment]
将config.json文件挂载到容器内部的/root目录下，具体的config.json请参考：https://github.com/myleo1/JDC-Monitor/blob/master/config.json

**Comment by QinChBeSt** [comment]
这个部署好了，但现在一直连不上数据库，ERROR   exception: Post "http://localhost:8086//write?db=jdc&u=admin&p=qiancheng": dial tcp 127.0.0.1:8086: connect: connection refused，在grafana直接连这个数据库，也是连不上，我是在macOS的docker运行的。influxdb数据库我应该选什么版本？哪里需要特殊设置吗？请指教。。。

**Comment by myleo1** [comment]
估计是docker网络的问题，这里不能用localhost或者127.0.0.1，要用influxdb那个容器的ip，或者配置一下几个容器的网络即可

**Comment by QinChBeSt** [comment]
influxdbd的版本我需要用哪个版本？我看说1.7以前和后面的写数据的语法不一样.

**Comment by myleo1** [comment]
我这边用的1.7-alpine

**Comment by QinChBeSt** [comment]
我把地址用了本机IP，现在可以连接上了，但是又报错ERROR   exception: 获取路由器状态失败，检查了tgt参数是对的。

**Comment by myleo1** [comment]
app里有失联的无线宝吗？最近一代出问题了，好像app里也获取不到状态

**Comment by QinChBeSt** [comment]
现在GRAFANA 又一直开始报这个错了。。。  logger=context userId=0 orgId=0 uname= t=2023-08-11T10:57:14.503076759+08:00 level=info msg="Request Completed" method=POST path=/:8086//write status=302 remote_addr=172.17.0.1 time_ms=2 duration=2.730097ms size=0 referer= handler=notfound

**Comment by QinChBeSt** [comment]
你好，这个调整获取数据的频路是调整哪里的代码？没找到，求告知~谢谢~~~~

**Comment by myleo1** [comment]
搜一下func CollectTask即可
